// Supabase Edge Function: embed-learning
// Store learning in database (full-text search vector auto-generated)

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface LearningInput {
  slug: string;
  name: string;
  content: string;
  domains: string[];
  triggers?: string[];
  scan_patterns?: string[];
  task_types?: string[];
  source_url?: string;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    // Fall back to anon key if service key not set (requires permissive RLS)
    const supabaseKey = supabaseServiceKey || Deno.env.get("SUPABASE_ANON_KEY");

    if (!supabaseUrl || !supabaseKey) {
      throw new Error("Missing required environment variables");
    }

    const learning: LearningInput = await req.json();

    // Validate required fields
    if (!learning.slug || !learning.name || !learning.content || !learning.domains) {
      throw new Error("Missing required fields: slug, name, content, domains");
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    // Store learning - search_vector is auto-generated by PostgreSQL
    const { data, error } = await supabase
      .from("learnings")
      .upsert({
        slug: learning.slug,
        name: learning.name,
        content: learning.content,
        domains: learning.domains,
        triggers: learning.triggers || [],
        scan_patterns: learning.scan_patterns || [],
        task_types: learning.task_types || [],
        source_url: learning.source_url,
      }, {
        onConflict: "slug",
      })
      .select()
      .single();

    if (error) {
      throw new Error(`Supabase error: ${error.message}`);
    }

    return new Response(
      JSON.stringify({
        success: true,
        learning: {
          id: data.id,
          slug: data.slug,
          name: data.name,
        },
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 400,
      }
    );
  }
});
